### ISSUE TITLE
HTML version doesn't work on windows 10

### ISSUE THREAD

**Issue by Crutiatix** [nesbox/tic.computer#99]
This is proprably same bug as I reported in [the topic at itch.io forum](https://itch.io/t/52653/none-html-game-work). 
TIC starts up with a wird noise sound and after hovering with mouse turns into black screen.
I tried various browsers: Chrome, Firefox, Opera, Edge... All same.
This bug presists since I reported it at itch.io, so 1/3 of year.

Error traceback in console:
```javascript
v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:1 Uncaught Assertion failed: m->avail <= m->size, at: src/ext/blip_buf.c,190,blip_end_frame at Error
    at jsStackTrace (https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:1:24037)
    at stackTrace (https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:1:24220)
    at ___assert_fail (https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:1:1152172)
    at Array.jh (https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:8:77620)
    at mB (https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:17:59636)
    at Object.dynCall (https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:1:8131)
    at https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:1:1081583
    at Object.runIter (https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:1:1083113)
    at Browser_mainLoop_runner (https://v6p9d9t4.ssl.hwcdn.net/html/425986/tic.js:1:1081488)
```

**Comment by nesbox** [comment]
OK lets try to fix it
@Crutiatix could you pls unzip, run .html file and tell me what do you see?
[html.zip](https://github.com/nesbox/tic.computer/files/922220/html.zip)
Thanks

**Comment by Crutiatix** [comment]
Sure, here is output: 
![ticerrortest](https://cloud.githubusercontent.com/assets/17261132/25046512/2be2def4-2132-11e7-8ba9-582af7261e6d.jpg)
No errors in the console.

**Comment by nesbox** [comment]
I made a fix, pls test it (try to export html game and run it in the browser)
[tic.zip](https://github.com/nesbox/tic.computer/files/922331/tic.zip)

**Comment by Crutiatix** [comment]
Another error:
```javascript
cartridge.html:34 Uncaught abort() at Error
    at jsStackTrace (http://127.0.0.1:8080/cartridge.html:34:24037)
    at stackTrace (http://127.0.0.1:8080/cartridge.html:34:24220)
    at Object.abort (http://127.0.0.1:8080/cartridge.html:57:6102)
    at _abort (http://127.0.0.1:8080/cartridge.html:34:1117101)
    at rA (http://127.0.0.1:8080/cartridge.html:50:40889)
    at Iy (http://127.0.0.1:8080/cartridge.html:39:121334)
    at Hy (http://127.0.0.1:8080/cartridge.html:39:117245)
    at Array.Ay (http://127.0.0.1:8080/cartridge.html:39:107337)
    at qr (http://127.0.0.1:8080/cartridge.html:44:34534)
    at kh (http://127.0.0.1:8080/cartridge.html:42:83416)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```
This one is more like that which I reported at itch.io.

**Comment by nesbox** [comment]
ok, another one please
[html.zip](https://github.com/nesbox/tic.computer/files/922478/html.zip)

**Comment by Crutiatix** [comment]
```javascript
tic.js:1 pre-main prep time: 1 ms
3tic.js:1 Calling stub instead of sigaction()
tic.js:1 Uncaught abort() at Error
    at jsStackTrace (http://127.0.0.1:8080/tic.js:1:25371)
    at stackTrace (http://127.0.0.1:8080/tic.js:1:25554)
    at Object.abort (http://127.0.0.1:8080/tic.js:24:11978)
    at _abort (http://127.0.0.1:8080/tic.js:1:1120223)
    at WA (http://127.0.0.1:8080/tic.js:17:47016)
    at lz (http://127.0.0.1:8080/tic.js:5:132109)
    at kz (http://127.0.0.1:8080/tic.js:5:127938)
    at Array.dz (http://127.0.0.1:8080/tic.js:5:117775)
    at Vr (http://127.0.0.1:8080/tic.js:11:37800)
    at Ph (http://127.0.0.1:8080/tic.js:8:101173)
```
Same bahavior.

**Comment by nesbox** [comment]
Hmm, this one please
[html.zip](https://github.com/nesbox/tic.computer/files/922489/html.zip)

**Comment by nesbox** [comment]
@Crutiatix This should work I think, please test :)
[html.zip](https://github.com/nesbox/tic.computer/files/922512/html.zip)

**Comment by Crutiatix** [comment]
![works](https://cloud.githubusercontent.com/assets/17261132/25050941/750a9032-214a-11e7-8498-fa0111e66e7e.gif)
Good Work! :)

**Comment by nesbox** [comment]
Great, here is fixed exe, so you can export your html games until .22 wont be released
[tic.zip](https://github.com/nesbox/tic.computer/files/922625/tic.zip)
Thanks for your help :)
closing...
